#!/usr/bin/env bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

git pull origin master

function doIt() {
  ln -sf ${BASEDIR}/.bashrc ~/.bashrc
  ln -sf ${BASEDIR}/.fishrc ~/.fishrc
  ln -sf ${BASEDIR}/.gemrc ~/.gemrc
  ln -sf ${BASEDIR}/.gitconfig ~/.gitconfig
  ln -sf ${BASEDIR}/.gitignore_global ~/.gitignore_global
  ln -sf ${BASEDIR}/.irbrc ~/.irbrc
  ln -sf ${BASEDIR}/.railsrc ~/.railsrc
  ln -sf ${BASEDIR}/.tmux.conf ~/.tmux.conf
  ln -sf ${BASEDIR}/.vimrc ~/.vimrc

  source ~/.bashrc
  tmux-source ~/.tmux.conf
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
	doIt;
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1;
	echo "";
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		doIt;
	fi;
fi;
unset doIt;
